###
## GET all persons
GET {{host}}/api/v1/person
Accept: application/json

###

GET {{host}}/api/v1/person/10
Accept: application/json


###
## Add a person
POST {{host}}/api/v1/person
Content-Type: application/json

{
  "name": "Dhruv Mohindru",
  "message": "Hello from Dhruv"
}

###
## Update a person
PATCH {{host}}/api/v1/person/6
Content-Type: application/json

{
  "name": "Poonam Arora Mohindru",
  "message": "Hello from Poonam Arora Mohindru"
}

###
## Delete a person
DELETE  {{host}}/api/v1/person/6
Accept: application/json




