GET http://localhost:8090/api/v1/student?email=david@advancednavigation.com
Accept: application/json

###
POST http://localhost:8090/api/v1/student
Content-Type: application/json

{
  "firstName": "David",
  "lastName": "Stock",
  "email": "david@advancednavigation.com"
}


