server:
  port: 8980
spring:
  # Database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dhruv_testing
    username: postgres
    password: password
    hikari:
      minimumIdle: 1
      maximumPoolSize: 3
  # JPA configuration
  jpa:
    # PotGIS configuration
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

